"""init

Revision ID: 2313c36d67d4
Revises: 
Create Date: 2023-09-13 21:08:34.142589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2313c36d67d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nn_models',
    sa.Column('nn_model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('is_trained', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nn_model_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('path')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firebase_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('firebase_user_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_questionnaires',
    sa.Column('user_questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('favorite_category', sa.String(length=255), nullable=False),
    sa.Column('is_extrovert', sa.Boolean(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('educational_level', sa.Integer(), nullable=False),
    sa.Column('sports_interest', sa.Integer(), nullable=False),
    sa.Column('arts_interest', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_questionnaire_id'),
    sa.UniqueConstraint('user_id_fk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_questionnaires')
    op.drop_table('users')
    op.drop_table('nn_models')
    # ### end Alembic commands ###
