"""non unique username

Revision ID: 6b2a6ddea3bb
Revises: 2313c36d67d4
Create Date: 2023-09-20 20:33:34.328516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2a6ddea3bb'
down_revision: Union[str, None] = '2313c36d67d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nn_models', ['name'])
    op.drop_index('name', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'users', ['name'], unique=False)
    op.drop_constraint(None, 'nn_models', type_='unique')
    # ### end Alembic commands ###
